version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: infra-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: infra-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7
    container_name: infra-redis
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data

  mongo-orders:
    image: mongo:6
    container_name: infra-mongo-orders
    restart: always
    ports:
      - "${MONGO_ORDERS_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: orders_db
    volumes:
      - mongo_orders_data:/data/db

  mongo-payments:
    image: mongo:6
    container_name: infra-mongo-payments
    restart: always
    ports:
      - "${MONGO_PAYMENTS_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: payments_db
    volumes:
      - mongo_payments_data:/data/db

volumes:
  pgdata:
  mysqldata:
  redisdata:
  mongo_orders_data:
  mongo_payments_data:
