name: Deploy to EC2

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${GITHUB_REF##*/}" == "qa" ]]; then
            echo "ENV=qa" >> $GITHUB_ENV
            echo "EC2_HOST=${{ secrets.EC2_HOST_QA }}" >> $GITHUB_ENV
            echo "EC2_USER=${{ secrets.EC2_USER_QA }}" >> $GITHUB_ENV
            echo "${{ secrets.EC2_KEY_QA }}" > key.pem
          else
            echo "ENV=prod" >> $GITHUB_ENV
            echo "EC2_HOST=${{ secrets.EC2_HOST_PROD }}" >> $GITHUB_ENV
            echo "EC2_USER=${{ secrets.EC2_USER_PROD }}" >> $GITHUB_ENV
            echo "${{ secrets.EC2_KEY_PROD }}" > key.pem
          fi
          chmod 600 key.pem

      - name: Deploy via SSH
        run: |
          echo "Deploying to $ENV server ($EC2_HOST)"
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
            cd ~/inf
